.\" Copyright (c) 2003-2004 BalaBit IT Ltd.
.TH ZORP-CONFIG 5 "March 10, 2004"
.SH NAME
zorp-config \- Zorp compilation environment
.SH SYNOPSIS
zorp-config [\-\-prefix\fI[=DIR]\fP] [\-\-exec\-prefix\fI[=DIR]\fP] [\-\-version] [\-\-libs] [\-\-cflags]
.SH DESCRIPTION

Zorp is a new generation proxy firewall suite for Unix based operating
systems. 

\fIzorp-config\fP is a tool that is used to configure to determine
the compiler and linker flags that should be used to compile Zorp modules.

.SH OPTIONS

.TP
.B --prefix

.TP
.B --exec-prefix

.TP
.B --version

.TP
.B --cppflags

.TP
.B --cflags

.TP
.B --libs

.TP
.B --local-cppflags

.TP
.B --local-cflags

.TP
.B --local-libs

.TP
.B --datadir

.TP
.B --moduledir

.TP
.B --trace

.TP
.B --debug

.SH SEE ALSO
.BR zorp (8)
.SH AUTHOR
This manual page was written by Árpád Magosányi <mag@debian.org> and Balázs
Scheidler <bazsi@balabit.hu>.
